<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <AssemblyName>WolfAudioHelper</AssemblyName><RootNamespace>Renova123.WolfAudioHelper</RootNamespace>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="NAudio" Version="2.2.1" /></ItemGroup>
</Project>
