import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";

const root = new URL("../public/", import.meta.url);
const read = (file: string) => readFileSync(new URL(file, root), "utf8");

describe("THE WOLF single capture architecture", () => {
  it("keeps tabCapture ownership in background and removes legacy entry points", () => {
    const background = read("background.js");
    expect((background.match(/getMediaStreamId/g) || []).length).toBe(1);
    for (const legacy of ["WOLF_CAPTURE_TAB", "WOLF_CAPTURE_TAB_ID", "WOLF_START_TAB_STREAM", "WOLF_CAPTURE_STOP", "WOLF_TAB_ARMED"]) expect(background).not.toContain(legacy);
    expect(background).toContain("START_TAB_CAPTURE"); expect(background).toContain("captureId");
  });
  it("keeps playback and analysis as separate offscreen branches", () => { const offscreen = read("offscreen.js"); expect(offscreen).toContain("source.connect(audioContext.destination)"); expect(offscreen).toContain("source.connect(processor)"); expect(offscreen).toContain("ATTACH_CLIENT_SESSION"); });
  it("diagnoses real tab samples across channels without changing the audio API", () => { const offscreen = read("offscreen.js"); expect(offscreen).toContain("createAnalyser"); expect(offscreen).toContain("analyserRms"); expect(offscreen).toContain("input.numberOfChannels"); expect(offscreen).toContain("nonZeroSamples"); expect(offscreen).toContain("processor = audioContext.createScriptProcessor(4096, 2, 1)"); expect(offscreen).toContain("trackInfo(track)"); expect(offscreen).toContain("contextInfo()"); });
  it("keeps client audio on the local Whisper PCM contract", () => { const offscreen = read("offscreen.js"); expect(offscreen).toContain("SEND_SAMPLE_RATE = 24000"); expect(offscreen).toContain("encodePcm16"); expect(offscreen).toContain('sendFormat: "pcm16"'); expect(offscreen).toContain("sendChannels: 1"); expect(offscreen).not.toContain("clientSocket.send(mono.buffer)"); });
  it("makes capture reuse and auth reconciliation explicit", () => { const background = read("background.js"); const main = readFileSync(new URL("./main.ts", import.meta.url), "utf8"); expect(background).toContain("getCapturedTabs"); expect(background).toContain("captureStartInFlight"); expect(background).toContain("TAB_CAPTURE_REUSED"); expect(main).toContain("/wolf/session/active"); expect(main).toContain("AUTH_401"); expect(main).toContain("credentialSource"); });
  it("observes contact-panel changes without replacing the content script", () => { const content = read("content.js"); expect(content).toContain("MutationObserver"); expect(content).toContain("WOLF_CONTENT_CHANGED"); expect(content).toContain("normalizePhone"); expect(content).toContain("setTimeout(notifyChanged, 500)"); });
  it("keeps session cleanup separate from stream teardown", () => { const main = readFileSync(new URL("./main.ts", import.meta.url), "utf8"); expect(main).toContain("cleanupSession"); expect(main).toContain("stopMic"); expect(main).toContain("STOP_TAB_CAPTURE"); expect(main).not.toContain("tabArmed"); expect(main).not.toContain("WOLF_CAPTURE_STOP"); });
  it("uses one version source at build time", () => { const build = readFileSync(new URL("../scripts/copy-build.mjs", import.meta.url), "utf8"); expect(build).toContain("packageJson.version"); expect(build).toContain("manifest.version"); expect(build).not.toContain("replaceAll"); });
});

describe("THE WOLF UI performance", () => {
  it("mounts the DOM once and updates meters outside the UI tree", () => { const main = readFileSync(new URL("./main.ts", import.meta.url), "utf8"); expect((main.match(/app\.innerHTML/g) || []).length).toBe(1); expect(main).toContain("requestAnimationFrame"); expect(main).not.toContain("setInterval"); });
  it("keeps diagnosis and error actions in the stable DOM", () => { const main = readFileSync(new URL("./main.ts", import.meta.url), "utf8"); expect(main).toContain('id="diagnostics"'); expect(main).toContain("copyError"); expect(main).toContain("copyLogs"); expect(main).not.toContain("Extension: 0.1.4"); expect(main).not.toContain("Estratégia:"); });
  it("keeps action capture ahead of panel open", () => { const background = read("background.js"); expect(background).toContain("setPanelBehavior({ openPanelOnActionClick: false })"); expect(background.indexOf("await startTabCapture(tab)")).toBeLessThan(background.lastIndexOf("chrome.sidePanel.open({ tabId: tab.id })")); expect(background).toContain('emit("ACTION_CLICK"'); });
  it("opens the panel in the action gesture before async capture work", () => { const background = read("background.js"); const action = background.slice(background.indexOf("chrome.action.onClicked")); expect(action.indexOf('emit("SIDEPANEL_OPEN_REQUEST"')).toBeLessThan(action.indexOf("const panelPromise = chrome.sidePanel.open")); expect(action.indexOf("const panelPromise = chrome.sidePanel.open")).toBeLessThan(action.indexOf("void startTabCapture(tab)")); expect(action).toContain('emit("SIDEPANEL_OPEN_ERROR"'); });
  it("detects WhatsApp contact without requiring tab capture", () => { const main = readFileSync(new URL("./main.ts", import.meta.url), "utf8"); expect(main).toContain("activeWhatsAppTab"); expect(main).toContain("CONTENT_INJECTED"); expect(main).toContain("CURRENT_CHAT_DETECTED"); expect(main).toContain("/health/live"); expect(main).toContain("cta-reason"); });
  it("keeps client transcript and suggestion events separate from operator audio", () => { const main = readFileSync(new URL("./main.ts", import.meta.url), "utf8"); for (const event of ["CLIENT_TRANSCRIPT_PARTIAL", "CLIENT_TRANSCRIPT_FINAL", "SUGGESTION_TRIGGER", "QWEN_REQUEST_START", "QWEN_REQUEST_DONE", "SUGGESTION_RENDERED"]) expect(main).toContain(event); expect(main).toContain("handleClientTranscript"); expect(main).not.toContain('if (speaker === "client") { thinking'); });
  it("does not keep the session UI in preparation after LISTENING", () => { const main = readFileSync(new URL("./main.ts", import.meta.url), "utf8"); expect(main).toContain('snapshot.state === "LISTENING" || snapshot.state === "PAUSED"'); expect(main).toContain("Ouvindo conversa."); expect(main).toContain("Ouvindo conversa"); expect(main).toContain("if (!call) await detectContact()"); });
  it("supports armed activation and latest-wins streaming suggestions", () => { const main = readFileSync(new URL("./main.ts", import.meta.url), "utf8"); expect(main).toContain('"ARMED"'); expect(main).toContain("ACTIVATION_PHRASE_DETECTED"); expect(main).toContain("AUTO_SESSION_START"); expect(main).toContain("AbortController"); expect(main).toContain("DRAFT_SCHEDULED"); expect(main).toContain("QWEN_REQUEST_ABORTED"); expect(main).toContain("QWEN_FIRST_TOKEN"); expect(main).toContain("stream: true"); });
  it("keeps Whisper configured for Portuguese realtime recovery", () => { const service = readFileSync(new URL("../../../services/wolf-transcription/app.py", import.meta.url), "utf8"); expect(service).toContain("0.4"); expect(service).toContain("ENDPOINT_SILENCE_SECONDS = 0.55"); expect(service).toContain("PARTIAL_INTERVAL_SECONDS = float"); expect(service).toContain("ROLLING_WINDOW_SECONDS"); expect(service).toContain("stable_prefix"); expect(service).toContain("initial_prompt=INITIAL_PROMPT"); });
  it("keeps activation local and makes sales output spoken-only", () => { const main = readFileSync(new URL("./main.ts", import.meta.url), "utf8"); const prompt = readFileSync(new URL("../../api/src/the-wolf-prompt.ts", import.meta.url), "utf8"); expect(main).toContain("ACTIVATION_PHRASE_DETECTED"); expect(main).toContain("activationMatches"); expect(main).toContain("SESSION_CONTEXT_RESET"); expect(main).toContain("FAST_PATH_MATCH"); expect(main).toContain("SALES_PROMPT_REJECTED_META"); expect(prompt).toContain("Retorne somente a fala"); expect(prompt).toContain("agendamento de uma demonstração"); expect(prompt).not.toContain("JSON válido"); });
});
