import {
  Activity,
  ArchiveX,
  Ban,
  Bot,
  BrainCircuit,
  CalendarClock,
  CalendarDays,
  CircleOff,
  Clock3,
  FileUp,
  FolderKanban,
  Gauge,
  HeartHandshake,
  Import,
  Inbox,
  ListChecks,
  MessageCircleMore,
  MessageSquareText,
  ScrollText,
  Settings,
  SlidersHorizontal,
  Sparkles,
  UsersRound,
  Wifi,
} from "lucide-react";
import type { PageKey } from "@renova123/shared";
import { WolfIcon } from "./components/WolfIcon";

export type NavigationItem = { key: PageKey; path: string; label: string; icon: typeof Gauge; group: string };

export const navigation: NavigationItem[] = [
  {
    key: "wolfCalls",
    path: "/the-wolf",
    label: "THE WOLF",
    icon: WolfIcon as typeof Gauge,
    group: "Ligações",
  },
  { key: "overview", path: "/dashboard", label: "Visão geral", icon: Gauge, group: "Operação" },
  { key: "flow", path: "/fluxo", label: "Fluxo", icon: SlidersHorizontal, group: "Operação" },
  { key: "leads", path: "/leads", label: "Leads", icon: UsersRound, group: "Operação" },
  { key: "imports", path: "/importacoes", label: "Importações", icon: Import, group: "Operação" },
  { key: "batches", path: "/lotes", label: "Lotes de captação", icon: FolderKanban, group: "Operação" },
  { key: "queue", path: "/fila", label: "Fila de envios", icon: ListChecks, group: "Operação" },
  {
    key: "conversations",
    path: "/conversas",
    label: "Conversas",
    icon: MessageCircleMore,
    group: "Relacionamento",
  },
  {
    key: "interested",
    path: "/interessados",
    label: "Interessados",
    icon: HeartHandshake,
    group: "Relacionamento",
  },
  { key: "qualified", path: "/qualificados", label: "Qualificados", icon: HeartHandshake, group: "Relacionamento" },
  {
    key: "demos",
    path: "/demonstracoes",
    label: "Demonstrações",
    icon: CalendarDays,
    group: "Relacionamento",
  },
  {
    key: "unanswered",
    path: "/nao-responderam",
    label: "Não responderam",
    icon: CircleOff,
    group: "Relacionamento",
  },
  { key: "followups", path: "/follow-ups", label: "Follow-ups", icon: Clock3, group: "Relacionamento" },
  {
    key: "handoffs",
    path: "/transferencias",
    label: "Transferências",
    icon: UsersRound,
    group: "Relacionamento",
  },
  { key: "lost", path: "/perdidos", label: "Perdidos", icon: ArchiveX, group: "Relacionamento" },
  { key: "optouts", path: "/opt-outs", label: "Opt-outs", icon: Ban, group: "Relacionamento" },
  { key: "materials", path: "/materiais", label: "Materiais", icon: FileUp, group: "Francisco" },
  {
    key: "knowledge",
    path: "/base-conhecimento",
    label: "Base de conhecimento",
    icon: BrainCircuit,
    group: "Francisco",
  },
  { key: "mind", path: "/mente-da-ia", label: "Mente da IA", icon: BrainCircuit, group: "Francisco" },
  {
    key: "openers",
    path: "/mensagens-iniciais",
    label: "Mensagens iniciais",
    icon: MessageSquareText,
    group: "Francisco",
  },
  {
    key: "schedule",
    path: "/horarios-limites",
    label: "Horários e limites",
    icon: CalendarClock,
    group: "Configuração",
  },
  { key: "groq", path: "/integracoes/groq", label: "GroqCloud", icon: Sparkles, group: "Configuração" },
  { key: "whatsapp", path: "/integracoes/whatsapp", label: "WhatsApp", icon: Wifi, group: "Configuração" },
  { key: "health", path: "/saude", label: "Saúde do sistema", icon: Activity, group: "Configuração" },
  { key: "logs", path: "/logs", label: "Logs e auditoria", icon: ScrollText, group: "Configuração" },
  {
    key: "settings",
    path: "/configuracoes",
    label: "Configurações gerais",
    icon: Settings,
    group: "Configuração",
  },
];

export const pageMeta: Record<
  PageKey,
  { eyebrow: string; title: string; description: string; icon: typeof Bot }
> = {
  wolfLeadStates: {
    eyebrow: "THE WOLF",
    title: "Estado operacional",
    description: "Estado dos leads de ligação.",
    icon: WolfIcon as typeof Gauge,
  },
  wolfCallEvents: {
    eyebrow: "THE WOLF",
    title: "Eventos de ligação",
    description: "Eventos operacionais das chamadas.",
    icon: WolfIcon as typeof Gauge,
  },
  wolfCalls: {
    eyebrow: "Central de ligações",
    title: "THE WOLF",
    description: "Sua mesa operacional para chamadas, retornos e resultados.",
    icon: WolfIcon as typeof Gauge,
  },
  overview: {
    eyebrow: "Operação em tempo real",
    title: "Visão geral",
    description: "Acompanhe a captação, as conversas e os próximos passos do Francisco.",
    icon: Gauge,
  },
  flow: {
    eyebrow: "Cadência comercial",
    title: "Fluxo",
    description: "Saiba onde cada contato está, quando volta para a fila e por que saiu da cadência.",
    icon: SlidersHorizontal,
  },
  leads: {
    eyebrow: "Base comercial",
    title: "Leads",
    description: "Consulte todos os contatos e o estágio atual de cada oportunidade.",
    icon: UsersRound,
  },
  imports: {
    eyebrow: "Entrada segura",
    title: "Importação",
    description: "Valide uma lista autorizada antes de adicioná-la à captação.",
    icon: Import,
  },
  batches: {
    eyebrow: "Organização",
    title: "Lotes de captação",
    description: "Priorize e acompanhe as origens de contatos autorizados.",
    icon: FolderKanban,
  },
  queue: {
    eyebrow: "Execução",
    title: "Fila de envios",
    description: "Veja tarefas pendentes, tentativas, retentativas e falhas definitivas.",
    icon: ListChecks,
  },
  conversations: {
    eyebrow: "Inbox",
    title: "Conversas",
    description: "Histórico do WhatsApp e contexto comercial de cada lead.",
    icon: Inbox,
  },
  interested: {
    eyebrow: "Oportunidades",
    title: "Interessados",
    description: "Leads que demonstraram aderência ao Renova 123.",
    icon: HeartHandshake,
  },
  qualified: {
    eyebrow: "Oportunidades qualificadas",
    title: "Qualificados",
    description: "Leads qualificados pelo Francisco e prontos para atendimento humano.",
    icon: HeartHandshake,
  },
  demos: {
    eyebrow: "Agenda comercial",
    title: "Demonstrações",
    description: "Crie, remarque, atribua e acompanhe demonstrações.",
    icon: CalendarDays,
  },
  unanswered: {
    eyebrow: "Acompanhamento",
    title: "Não responderam",
    description: "Contatos abordados que ainda não responderam.",
    icon: CircleOff,
  },
  followups: {
    eyebrow: "Cadência",
    title: "Follow-ups",
    description: "Próximos contatos recomendados e programados.",
    icon: Clock3,
  },
  handoffs: {
    eyebrow: "Atendimento humano",
    title: "Transferidos",
    description: "Conversas pausadas para ação da equipe comercial.",
    icon: UsersRound,
  },
  lost: {
    eyebrow: "Histórico",
    title: "Perdidos",
    description: "Oportunidades encerradas e seus motivos.",
    icon: ArchiveX,
  },
  optouts: {
    eyebrow: "Supressão",
    title: "Opt-outs e bloqueios",
    description: "Números que não podem receber novas mensagens.",
    icon: Ban,
  },
  materials: {
    eyebrow: "Biblioteca",
    title: "Materiais",
    description: "Conteúdos autorizados que o Francisco pode recomendar.",
    icon: FileUp,
  },
  knowledge: {
    eyebrow: "Contexto confiável",
    title: "Base de conhecimento",
    description: "Textos, FAQ, regras e documentos comerciais usados pelo Francisco.",
    icon: BrainCircuit,
  },
  notifications: {
    eyebrow: "Alertas",
    title: "Notificações",
    description: "Eventos operacionais que pedem atenção.",
    icon: Activity,
  },
  mind: {
    eyebrow: "Conhecimento comercial",
    title: "Mente da IA",
    description: "Defina identidade, produto, regras e critérios do Francisco.",
    icon: BrainCircuit,
  },
  openers: {
    eyebrow: "Primeiro contato",
    title: "Mensagens iniciais",
    description: "Edite aberturas variadas que funcionam mesmo sem nome.",
    icon: MessageSquareText,
  },
  schedule: {
    eyebrow: "Controle operacional",
    title: "Horários e limites",
    description: "Configure cadência, dias e limites sem valores fixos no código.",
    icon: SlidersHorizontal,
  },
  groq: {
    eyebrow: "Modelo de linguagem",
    title: "Configuração da Groq",
    description: "Selecione o modelo e confira a disponibilidade do provedor único.",
    icon: Sparkles,
  },
  whatsapp: {
    eyebrow: "Evolution API",
    title: "Configuração do WhatsApp",
    description: "Conecte a única instância com QR Code e acompanhe o estado.",
    icon: Wifi,
  },
  health: {
    eyebrow: "Observabilidade",
    title: "Saúde do sistema",
    description: "Verifique API, banco, Groq, Evolution e segurança operacional.",
    icon: Activity,
  },
  logs: {
    eyebrow: "Rastreabilidade",
    title: "Logs e auditoria",
    description: "Ações importantes sem exposição de credenciais ou segredos.",
    icon: ScrollText,
  },
  settings: {
    eyebrow: "Sistema",
    title: "Configurações gerais",
    description: "Modo de simulação, parada geral e identidade do ambiente.",
    icon: Settings,
  },
};
