import {
  Activity,
  ArchiveX,
  Ban,
  Bot,
  BrainCircuit,
  CalendarClock,
  CalendarDays,
  CircleOff,
  Clock3,
  FileUp,
  FolderKanban,
  Gauge,
  HeartHandshake,
  Import,
  Inbox,
  ListChecks,
  MessageCircleMore,
  MessageSquareText,
  PhoneCall,
  ScrollText,
  Settings,
  SlidersHorizontal,
  Sparkles,
  UsersRound,
  Wifi,
} from "lucide-react";
import type { PageKey } from "@renova123/shared";

export type NavigationItem = { key: PageKey; path: string; label: string; icon: typeof Gauge; group: string };

export const navigation: NavigationItem[] = [
  { key: "overview", path: "/dashboard", label: "Visão geral", icon: Gauge, group: "Principal" },
  { key: "calls", path: "/ligacoes", label: "Ligações", icon: PhoneCall, group: "Principal" },
  { key: "flow", path: "/fluxo", label: "Fluxo", icon: SlidersHorizontal, group: "Principal" },
  { key: "leads", path: "/leads", label: "Leads", icon: UsersRound, group: "Principal" },
  { key: "conversations", path: "/conversas", label: "Conversas", icon: MessageCircleMore, group: "Principal" },
  { key: "interested", path: "/interessados", label: "Interessados", icon: HeartHandshake, group: "Comercial" },
  { key: "qualified", path: "/qualificados", label: "Qualificados", icon: HeartHandshake, group: "Comercial" },
  { key: "demos", path: "/demonstracoes", label: "Demonstrações", icon: CalendarDays, group: "Comercial" },
  { key: "imports", path: "/importacoes", label: "Importações", icon: Import, group: "Sistema" },
  { key: "whatsapp", path: "/integracoes/whatsapp", label: "WhatsApp", icon: Wifi, group: "Sistema" },
  { key: "settings", path: "/configuracoes", label: "Configurações", icon: Settings, group: "Sistema" },
];

export const pageMeta: Record<
  PageKey,
  { eyebrow: string; title: string; description: string; icon: typeof Bot }
> = {
  overview: {
    eyebrow: "Operação em tempo real",
    title: "Visão geral",
    description: "Acompanhe a captação, as conversas e os próximos passos do Francisco.",
    icon: Gauge,
  },
  calls: {
    eyebrow: "Rotina comercial",
    title: "Ligações",
    description: "Seu caderno diário de ligações, resultados, retornos e meta de 100 contatos.",
    icon: PhoneCall,
  },
  flow: {
    eyebrow: "Cadência comercial",
    title: "Fluxo",
    description: "Saiba onde cada contato está, quando volta para a fila e por que saiu da cadência.",
    icon: SlidersHorizontal,
  },
  leads: {
    eyebrow: "Base comercial",
    title: "Leads",
    description: "Consulte todos os contatos e o estágio atual de cada oportunidade.",
    icon: UsersRound,
  },
  imports: {
    eyebrow: "Entrada segura",
    title: "Importação",
    description: "Valide uma lista autorizada antes de adicioná-la à captação.",
    icon: Import,
  },
  batches: {
    eyebrow: "Organização",
    title: "Lotes de captação",
    description: "Priorize e acompanhe as origens de contatos autorizados.",
    icon: FolderKanban,
  },
  queue: {
    eyebrow: "Execução",
    title: "Fila de envios",
    description: "Veja tarefas pendentes, tentativas, retentativas e falhas definitivas.",
    icon: ListChecks,
  },
  conversations: {
    eyebrow: "Inbox",
    title: "Conversas",
    description: "Histórico do WhatsApp e contexto comercial de cada lead.",
    icon: Inbox,
  },
  interested: {
    eyebrow: "Oportunidades",
    title: "Interessados",
    description: "Leads que demonstraram aderência ao Renova 123.",
    icon: HeartHandshake,
  },
  qualified: {
    eyebrow: "Oportunidades qualificadas",
    title: "Qualificados",
    description: "Leads qualificados pelo Francisco e prontos para atendimento humano.",
    icon: HeartHandshake,
  },
  demos: {
    eyebrow: "Agenda comercial",
    title: "Demonstrações",
    description: "Crie, remarque, atribua e acompanhe demonstrações.",
    icon: CalendarDays,
  },
  unanswered: {
    eyebrow: "Acompanhamento",
    title: "Não responderam",
    description: "Contatos abordados que ainda não responderam.",
    icon: CircleOff,
  },
  followups: {
    eyebrow: "Cadência",
    title: "Follow-ups",
    description: "Próximos contatos recomendados e programados.",
    icon: Clock3,
  },
  handoffs: {
    eyebrow: "Atendimento humano",
    title: "Transferidos",
    description: "Conversas pausadas para ação da equipe comercial.",
    icon: UsersRound,
  },
  lost: {
    eyebrow: "Histórico",
    title: "Perdidos",
    description: "Oportunidades encerradas e seus motivos.",
    icon: ArchiveX,
  },
  optouts: {
    eyebrow: "Supressão",
    title: "Opt-outs e bloqueios",
    description: "Números que não podem receber novas mensagens.",
    icon: Ban,
  },
  materials: {
    eyebrow: "Biblioteca",
    title: "Materiais",
    description: "Conteúdos autorizados que o Francisco pode recomendar.",
    icon: FileUp,
  },
  knowledge: {
    eyebrow: "Contexto confiável",
    title: "Base de conhecimento",
    description: "Textos, FAQ, regras e documentos comerciais usados pelo Francisco.",
    icon: BrainCircuit,
  },
  notifications: {
    eyebrow: "Alertas",
    title: "Notificações",
    description: "Eventos operacionais que pedem atenção.",
    icon: Activity,
  },
  mind: {
    eyebrow: "Conhecimento comercial",
    title: "Mente da IA",
    description: "Defina identidade, produto, regras e critérios do Francisco.",
    icon: BrainCircuit,
  },
  openers: {
    eyebrow: "Primeiro contato",
    title: "Mensagens iniciais",
    description: "Edite aberturas variadas que funcionam mesmo sem nome.",
    icon: MessageSquareText,
  },
  schedule: {
    eyebrow: "Controle operacional",
    title: "Horários e limites",
    description: "Configure cadência, dias e limites sem valores fixos no código.",
    icon: SlidersHorizontal,
  },
  groq: {
    eyebrow: "Modelo de linguagem",
    title: "Configuração da Groq",
    description: "Selecione o modelo e confira a disponibilidade do provedor único.",
    icon: Sparkles,
  },
  whatsapp: {
    eyebrow: "Evolution API",
    title: "Configuração do WhatsApp",
    description: "Acompanhe Francisco e Pedro em instâncias WhatsApp independentes.",
    icon: Wifi,
  },
  health: {
    eyebrow: "Observabilidade",
    title: "Saúde do sistema",
    description: "Verifique API, banco, Groq, Evolution e segurança operacional.",
    icon: Activity,
  },
  logs: {
    eyebrow: "Rastreabilidade",
    title: "Logs e auditoria",
    description: "Ações importantes sem exposição de credenciais ou segredos.",
    icon: ScrollText,
  },
  settings: {
    eyebrow: "Sistema",
    title: "Configurações gerais",
    description: "Modo de simulação, parada geral e identidade do ambiente.",
    icon: Settings,
  },
};
