import { describe, expect, it } from "vitest";
import type { AiDecision } from "@renova123/shared";
import { AgentContextBuilder } from "./agent/agent-context-builder.js";
import { AgentDecisionValidator } from "./agent/agent-decision-validator.js";
import { deriveConversationState, extractExplicitLeadName } from "./agent/conversation-state.js";
import { APPROVED_SOCIAL_PROOF, enforceProductGrounding, CONFIRMED_PRODUCT_CATALOG } from "./agent/product-grounding.js";
import type { AgentSnapshot } from "./agent/types.js";
import { canAttemptGroupDelivery, formatQualifiedGroupMessage, groupNotificationDedupKey } from "./group-notifications.js";

const base: AgentSnapshot = { mind: {}, commercial: {}, lead: {}, batch: {}, stage: "engaged", summary: "", messages: [], memories: [], materials: [], availableSlots: [], followUps: [], questionsAsked: [], materialsSent: [], humanActive: false, automationPaused: false, blocked: false };
const facts = [
  { key: "professional_category", value: "owner_responsible", evidenceType: "explicit", confidence: 1 },
  { key: "main_pain", value: "orçamentos se perdem", evidenceType: "explicit", confidence: 1 },
] satisfies AiDecision["memoryUpdates"];
const decision = (overrides: Partial<AiDecision> = {}): AiDecision => ({ replyText: "Certo.", leadStage: "interested", detectedIntent: "information", sentiment: "positive", summaryUpdate: null, memoryUpdates: [], questionsAnswered: [], objectionsDetected: [], shouldSendMaterial: false, materialQuery: null, shouldProposeDemo: false, suggestedSlots: [], shouldScheduleDemo: false, appointmentData: null, shouldHandoff: false, handoffReason: null, shouldOptOut: false, followUpAction: { action: "none", delayHours: null, reason: "aguardar" }, confidence: .9, internalReasoningSummary: "operacional", qualificationStatus: "discovering", handoffType: null, qualificationScore: 0, mariliaConsent: "not_asked", ...overrides });

describe("21 regressões comerciais obrigatórias", () => {
  it("1 registra volume impreciso como tópico já respondido", () => expect(deriveConversationState({ ...base, memories: [{ key: "answered_questions", value: "volume informado sem quantidade exata", evidenceType: "explicit" }] }, "Não sei o número exato, muitos.").answeredTopics).toContain("volume informado sem quantidade exata"));
  it("2 interpreta 'Legal isso aí' como interesse", () => expect(new AgentDecisionValidator().validate(decision({ memoryUpdates: facts }), base).decision.qualificationScore).toBeLessThan(new AgentDecisionValidator().validate(decision({ memoryUpdates: facts }), { ...base, messages: [{ role: "lead", text: "Legal isso aí." }] }).decision.qualificationScore));
  it("3 interesse não força consentimento se o SDR ainda não propôs demo", () => expect(new AgentDecisionValidator().validate(decision({ memoryUpdates: facts }), { ...base, messages: [{ role: "lead", text: "Gosto, pode mostrar." }] }).decision.mariliaConsent).toBe("not_asked"));
  it("4 estado informa a dor sem impor quantidade de perguntas", () => { const state = deriveConversationState({ ...base, memories: [{ key: "main_pain", value: "dor", evidenceType: "explicit" }] }, "sim"); expect(state.painConfirmed).toBe(true); expect(state).not.toHaveProperty("discoveryQuestionsRemaining"); });
  it("5 não prescreve bordão e orienta o mínimo necessário", () => { const prompt = new AgentContextBuilder().build(base, "sim").systemPrompt; expect(prompt).toContain("mínimo de texto necessário"); expect(prompt).not.toContain("Evite começar respostas seguidas"); });
  it("6 prospect novo tem nome desconhecido", () => expect(deriveConversationState(base, "oi").leadNameKnown).toBe(false));
  it("7 pushName interno não vira nome confirmado", () => expect(new AgentContextBuilder().build({ ...base, lead: { name: "Pedro Push" } }, "oi").selected.lead ?? {}).not.toHaveProperty("name"));
  it("8 nome informado pelo lead é extraído para persistência", () => expect(extractExplicitLeadName("Meu nome é Pedro Silva")).toBe("Pedro Silva"));
  it("9 origem do contato só aparece como proveniência real", () => expect(new AgentContextBuilder().build({ ...base, lead: { source: "Feira Óptica" } }, "Como sabe meu nome?").selected.provenance).toEqual({ source: "Feira Óptica" }));
  it("10 catálogo confirma proposta, PDF e WhatsApp", () => expect(CONFIRMED_PRODUCT_CATALOG.budgets.join(" ")).toMatch(/proposta[\s\S]*PDF[\s\S]*WhatsApp/i));
  it("11 bloqueia follow-up automático de orçamento", () => expect(enforceProductGrounding(decision({ replyText: "O follow-up automático do orçamento chama o cliente." })).replyText).toContain("Pedro"));
  it("12 não emite 30% sem fonte", () => expect(enforceProductGrounding(decision({ replyText: "Você ganha 30% mais." })).replyText).not.toContain("30%"));
  it("13 não emite 5 minutos sem fonte", () => expect(enforceProductGrounding(decision({ replyText: "Implanta em 5 minutos." })).replyText).not.toContain("5 minutos"));
  it("14 Maceió não vira Alagoas", () => expect(enforceProductGrounding(decision({ replyText: "Atendemos mais de 30 óticas em Alagoas." })).replyText).not.toContain("Alagoas"));
  it("15 'Pode sim' conclui handoff imediato", () => expect(new AgentDecisionValidator().validate(decision({ detectedIntent: "demo", memoryUpdates: facts, mariliaConsent: "pending" }), { ...base, mariliaConsent: "pending", memories: facts, messages: [{ role: "lead", text: "Pode sim" }] }).decision).toMatchObject({ qualificationStatus: "qualified", shouldHandoff: true }));
  it("16 depois do consentimento não pergunta de novo", () => expect(new AgentDecisionValidator().validate(decision({ replyText: "Posso passar para a Marília?" }), { ...base, qualificationStatus: "qualified", qualificationScore: 100, mariliaConsent: "granted" }).decision.replyText).not.toContain("Posso passar"));
  it("17 retry usa a mesma chave e sent não tenta de novo", () => { expect(groupNotificationDedupKey("lead_interested", "1")).toBe(groupNotificationDedupKey("lead_interested", "1")); expect(canAttemptGroupDelivery("sent")).toBe(false); });
  it("18 grupo não expõe campos técnicos", () => expect(formatQualifiedGroupMessage({ name: "Ana" })).not.toMatch(/qualification_status|rollingSummary|memoryUpdates|lead_id/i));
  it("19 grupo é humano, curto e seccionado", () => { const body = formatQualifiedGroupMessage({ name: "Ana", mainPain: "orçamentos" }); expect(body).toContain("CONTEXTO DA CONVERSA"); expect(body).toContain("PRINCIPAL INTERESSE"); expect(body.length).toBeLessThan(900); });
  it("20 após handoff o estado lembra que Marília já recebeu", () => { const snap = { ...base, qualificationStatus: "qualified" as const, mariliaConsent: "granted" as const }; expect(deriveConversationState(snap, "tenho uma dúvida").handoffCompleted).toBe(true); });
  it("21 handoff acontece uma vez e respostas seguintes não repetem o encaminhamento", () => { const first = new AgentDecisionValidator().validate(decision({ detectedIntent: "demo", memoryUpdates: facts, mariliaConsent: "granted" }), base).decision; const second = new AgentDecisionValidator().validate(decision({ replyText: first.replyText }), { ...base, qualificationStatus: "qualified", mariliaConsent: "granted" }).decision; expect(first.shouldHandoff).toBe(true); expect(second.shouldHandoff).toBe(false); expect(second.replyText).not.toMatch(/vou repassar seu interesse/i); });
  it("22 nome e ótica não viram bloqueio burocrático depois do consentimento", () => expect(new AgentDecisionValidator().validate(decision({ detectedIntent: "demo", memoryUpdates: facts, mariliaConsent: "granted" }), { ...base, lead: { id: "1" }, messages: [{ role: "lead", text: "Pode sim" }], mariliaConsent: "pending" }).decision).toMatchObject({ qualificationStatus: "qualified", shouldHandoff: true }));
  it("23 dá liberdade, conecta valor e prioriza pergunta direta", () => { const prompt = new AgentContextBuilder().build(base, "como funciona?").systemPrompt; expect(prompt).toContain("escolha livremente o próximo movimento"); expect(prompt).toContain("conectar uma capacidade confirmada"); expect(prompt).toContain("Responda à pergunta direta primeiro"); });
  it("24 busca nome e ótica naturalmente sem cadastro em sequência", () => { const prompt = new AgentContextBuilder().build(base, "oi").systemPrompt; expect(prompt).toContain("Nome e ótica são úteis"); expect(prompt).toContain("nunca como cadastro em sequência"); });
  it("25 prova social regional tem escopo aprovado e DDD não confirma cidade", () => { const built = new AgentContextBuilder().build({ ...base, lead: { phone: "5582988543864" } }, "sou de Alagoas"); expect(built.selected.locationHint).toMatchObject({ ddd: "82", probableState: "Alagoas", cityConfirmed: false }); expect(APPROVED_SOCIAL_PROOF).toEqual(expect.arrayContaining([expect.objectContaining({ scope: "city", city: "Maceió" })])); expect(APPROVED_SOCIAL_PROOF).not.toEqual(expect.arrayContaining([expect.objectContaining({ scope: "state", state: "Alagoas" })])); });
  it("26 catálogo geral só usa capacidades documentadas", () => expect(CONFIRMED_PRODUCT_CATALOG.overview.examples.join(" ")).toMatch(/estoque.*financeiro.*histórico/i));
  it("27 catálogo não inventa simulador de lentes", () => expect(JSON.stringify(CONFIRMED_PRODUCT_CATALOG)).not.toMatch(/simulador de lentes/i));
});
