import { useEffect, useMemo, useState, type FormEvent } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, List, Pencil, Plus, RotateCw, XCircle } from "lucide-react";
import { Button, DataTable, FilterBar, Modal, SearchInput, StatusBadge } from "@renova123/ui";
import { api } from "../api";
import { Feedback } from "../components/Feedback";
import { PageHeader } from "../components/PageHeader";

type Appointment = { id: string; leadId?: string; lead?: string; company?: string; conversationId?: string; startsAt: string; endsAt?: string; status: string; assignee?: string; notes?: string; origin?: "ai" | "manual"; reminderAt?: string };
const statuses = ["requested", "proposed", "confirmed", "cancelled", "completed", "no_show", "rescheduled"];

export function AppointmentsPage() {
  const [rows, setRows] = useState<Appointment[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [closer, setCloser] = useState("");
  const [mode, setMode] = useState<"calendar" | "list">("calendar"); const [cursor, setCursor] = useState(() => new Date()); const [selectedDay, setSelectedDay] = useState(dateKey(new Date()));
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Appointment | null>(null); const [reschedule, setReschedule] = useState<Appointment | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { try { setRows((await api<{ rows: Appointment[] }>(`/appointments?page=1&pageSize=100&search=${encodeURIComponent(search)}`)).rows); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao carregar agenda."); } }
  useEffect(() => { void load(); }, [search]);
  const visible = useMemo(() => rows.filter((item) => (!status || item.status === status) && (!closer || item.assignee === closer)), [rows, status, closer]);
  const calendarDays = useMemo(() => monthDays(cursor), [cursor]);
  async function save(event: FormEvent<HTMLFormElement>, target = editing) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const startsAt = new Date(String(data.startsAt)).toISOString(); const endsAt = new Date(String(data.endsAt)).toISOString(); if (new Date(endsAt) <= new Date(startsAt)) return setError("O término deve ser posterior ao início."); const conflict = rows.find((item) => item.id !== target?.id && !["cancelled", "completed", "no_show"].includes(item.status) && startsAt < (item.endsAt ?? item.startsAt) && endsAt > item.startsAt); if (conflict) return setError(`Conflito com ${conflict.lead ?? conflict.assignee ?? "outro compromisso"}.`); const body = { leadId: data.leadId, conversationId: data.conversationId || null, startsAt, endsAt, status: data.status, assignee: data.assignee, notes: data.notes, origin: data.origin, reminderAt: data.reminderAt ? new Date(String(data.reminderAt)).toISOString() : null }; try { await api(target ? `/resources/demos/${target.id}` : "/resources/demos", { method: target ? "PATCH" : "POST", body: JSON.stringify(body) }); setMessage(target ? "Agendamento atualizado." : "Agendamento criado."); setOpen(false); setEditing(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao salvar."); } }
  async function changeStatus(item: Appointment, next: string) { try { await api(`/resources/demos/${item.id}`, { method: "PATCH", body: JSON.stringify({ status: next, ...(next === "cancelled" ? { cancelledAt: new Date().toISOString() } : {}) }) }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao alterar status."); } }
  async function doReschedule(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!reschedule) return; const data = Object.fromEntries(new FormData(event.currentTarget)); try { await api(`/appointments/${reschedule.id}/reschedule`, { method: "POST", body: JSON.stringify({ startsAt: new Date(String(data.startsAt)).toISOString(), endsAt: new Date(String(data.endsAt)).toISOString(), notes: data.notes }) }); setReschedule(null); setMessage("Horário reagendado e registrado no histórico."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Conflito ou falha no reagendamento."); } }
  const actions = (item: Appointment) => <AppointmentActions edit={() => { setEditing(item); setOpen(true); }} reschedule={() => setReschedule(item)} cancel={() => void changeStatus(item, "cancelled")} />;
  return <div className="page-stack"><PageHeader pageKey="demos" actions={<><div className="view-toggle"><button className={mode === "calendar" ? "active" : ""} aria-label="Calendário" onClick={() => setMode("calendar")}><CalendarDays /></button><button className={mode === "list" ? "active" : ""} aria-label="Lista" onClick={() => setMode("list")}><List /></button></div><Button onClick={() => setOpen(true)}><Plus /> Agendar</Button></>} />
    {error ? <Feedback kind="error" message={error} onClose={() => setError("")} /> : null}{message ? <Feedback kind="success" message={message} onClose={() => setMessage("")} /> : null}
    <FilterBar><SearchInput value={search} onChange={setSearch} placeholder="Buscar lead, closer ou observação" /><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos os status</option>{statuses.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select><select value={closer} onChange={(event) => setCloser(event.target.value)}><option value="">Todos os closers</option>{[...new Set(rows.map((item) => item.assignee).filter(Boolean))].map((item) => <option key={item}>{item}</option>)}</select></FilterBar>
    {mode === "calendar" ? <section className="appointment-calendar card"><header><button aria-label="Mês anterior" onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() - 1, 1))}><ChevronLeft /></button><h2>{cursor.toLocaleDateString("pt-BR", { month: "long", year: "numeric" })}</h2><button onClick={() => { const today = new Date(); setCursor(today); setSelectedDay(dateKey(today)); }}>Hoje</button><button aria-label="Próximo mês" onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1))}><ChevronRight /></button></header><div className="calendar-weekdays">{["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-month-grid">{calendarDays.map((date) => { const key = dateKey(date); const events = visible.filter((item) => dateKey(new Date(item.startsAt)) === key).sort((a, b) => a.startsAt.localeCompare(b.startsAt)); return <button key={key} className={`calendar-day ${date.getMonth() !== cursor.getMonth() ? "outside" : ""} ${key === dateKey(new Date()) ? "today" : ""} ${selectedDay === key ? "selected" : ""}`} onClick={() => setSelectedDay(key)} aria-label={`${date.toLocaleDateString("pt-BR")}: ${events.length} compromissos`}><span>{date.getDate()}</span>{events.slice(0, 2).map((item) => <i className="calendar-chip" key={item.id} title={`${time(item.startsAt)} ${item.lead ?? item.assignee ?? "Compromisso"}`}>{time(item.startsAt)} {item.lead ?? item.assignee ?? "Compromisso"}</i>)}{events.length > 2 ? <em>+{events.length - 2}</em> : null}</button>; })}</div><div className="selected-day-events"><h3>{new Date(`${selectedDay}T12:00:00`).toLocaleDateString("pt-BR", { dateStyle: "full" })}</h3>{visible.filter((item) => dateKey(new Date(item.startsAt)) === selectedDay).map((item) => <article key={item.id}><time>{time(item.startsAt)}</time><div><strong>{item.lead ?? "Lead vinculado"}</strong><small>{item.assignee || "Sem closer"} • {label(item.status)}</small></div>{actions(item)}</article>)}</div></section> : <DataTable rows={visible} rowKey={(row) => row.id} columns={[{ key: "when", label: "Quando", render: (row) => new Date(row.startsAt).toLocaleString("pt-BR") }, { key: "lead", label: "Lead", render: (row) => row.lead ?? row.leadId ?? "—" }, { key: "closer", label: "Closer", render: (row) => row.assignee ?? "—" }, { key: "status", label: "Status", render: (row) => <StatusBadge>{label(row.status)}</StatusBadge> }, { key: "actions", label: "Ações", render: actions }]} />}
    <AppointmentModal open={open} item={editing} close={() => { setOpen(false); setEditing(null); }} submit={(event) => void save(event)} />
    <Modal open={Boolean(reschedule)} title="Reagendar demonstração" onClose={() => setReschedule(null)}><form className="operational-form" onSubmit={(event) => void doReschedule(event)}><label>Novo início<input name="startsAt" type="datetime-local" required /></label><label>Novo término<input name="endsAt" type="datetime-local" required /></label><label>Motivo/observação<textarea name="notes" rows={3} /></label><footer className="modal-form-actions"><Button>Confirmar reagendamento</Button></footer></form></Modal>
  </div>;
}

function AppointmentModal({ open, item, close, submit }: { open: boolean; item: Appointment | null; close: () => void; submit: (event: FormEvent<HTMLFormElement>) => void }) { return <Modal open={open} title={item ? "Editar agendamento" : "Nova demonstração"} onClose={close} size="large"><form className="operational-form" onSubmit={submit}><div className="form-grid compact"><label>ID do lead<input name="leadId" required defaultValue={item?.leadId} /></label><label>ID da conversa<input name="conversationId" defaultValue={item?.conversationId} /></label><label>Início<input name="startsAt" type="datetime-local" required defaultValue={local(item?.startsAt)} /></label><label>Término<input name="endsAt" type="datetime-local" required defaultValue={local(item?.endsAt)} /></label><label>Status<select name="status" defaultValue={item?.status ?? "requested"}>{statuses.map((status) => <option key={status} value={status}>{label(status)}</option>)}</select></label><label>Closer<input name="assignee" defaultValue={item?.assignee} /></label><label>Origem<select name="origin" defaultValue={item?.origin ?? "manual"}><option value="manual">Manual</option><option value="ai">Francisco/IA</option></select></label><label>Lembrete<input name="reminderAt" type="datetime-local" defaultValue={local(item?.reminderAt)} /></label></div><label>Observações<textarea name="notes" rows={4} defaultValue={item?.notes} /></label><footer className="modal-form-actions"><Button type="button" variant="secondary" onClick={close}>Cancelar</Button><Button>Salvar</Button></footer></form></Modal>; }
function AppointmentActions({ edit, reschedule, cancel }: { edit: () => void; reschedule: () => void; cancel: () => void }) { return <div className="row-actions"><button aria-label="Editar" onClick={edit}><Pencil /></button><button aria-label="Reagendar" onClick={reschedule}><RotateCw /></button><button aria-label="Cancelar" onClick={cancel}><XCircle /></button></div>; }
function local(value?: string) { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
function label(value: string) { return ({ requested: "Solicitado", proposed: "Proposto", confirmed: "Confirmado", cancelled: "Cancelado", completed: "Concluído", no_show: "Não compareceu", rescheduled: "Reagendado", pending: "Pendente", scheduled: "Agendado" } as Record<string, string>)[value] ?? value; }
function dateKey(value: Date) { return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`; }
function time(value: string) { return new Date(value).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" }); }
function monthDays(cursor: Date) { const first = new Date(cursor.getFullYear(), cursor.getMonth(), 1); const start = new Date(first); start.setDate(1 - first.getDay()); return Array.from({ length: 42 }, (_, index) => { const day = new Date(start); day.setDate(start.getDate() + index); return day; }); }
