import { useEffect, useMemo, useState } from "react";
import { Activity, CheckCircle2, Gauge, KeyRound, Play, RefreshCw, Save, Sparkles, TriangleAlert } from "lucide-react";
import { api } from "../api";
import { Feedback, SkeletonTable } from "../components/Feedback";
import { PageHeader } from "../components/PageHeader";

type Model = { id: string; ownedBy: string; transcription: boolean };
type Limits = { limitRequests: number | null; limitTokens: number | null; remainingRequests: number | null; remainingTokens: number | null; resetRequests: string | null; resetTokens: string | null; observedAt: string };
type GroqStatus = { configured: boolean; apiKeyMasked: string; model: string; transcriptionModel: string; temperature: number; models: Model[]; health: { ok: boolean; latencyMs: number; modelCount: number; error: string | null; rateLimits: Limits | null }; lastFailure: string | null; processingPaused: boolean };
type AiStatus = { groq: "online" | "offline" | "cooldown"; gemini: "online" | "offline"; callsToday: number; fallbacksToday: number; finalFailuresToday: number };

export function GroqPage() {
  const [aiStatus, setAiStatus] = useState<AiStatus | null>(null);
  const [status, setStatus] = useState<GroqStatus | null>(null); const [key, setKey] = useState(""); const [model, setModel] = useState(""); const [transcriptionModel, setTranscriptionModel] = useState(""); const [temperature, setTemperature] = useState(0.3); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(""); const [models, setModels] = useState<Model[]>([]);
  async function load() { try { const result = await api<GroqStatus>("/groq/status"); setStatus(result); setModels(result.models); setModel(result.model); setTranscriptionModel(result.transcriptionModel); setTemperature(result.temperature); setAiStatus(await api<AiStatus>("/ai/status")); setError(""); } catch (reason) { setError(message(reason)); } }
  useEffect(() => { void load(); }, []);
  const chatModels = useMemo(() => models.filter((item) => !item.transcription), [models]);
  const whisperModels = useMemo(() => models.filter((item) => item.transcription), [models]);
  async function validate() { if (!key) { setError("Informe a chave para validar."); return; } setBusy("validate"); setError(""); try { const result = await api<{ models: Model[]; apiKeyMasked: string }>("/groq/validate", { method: "POST", body: JSON.stringify({ apiKey: key }) }); setModels(result.models); setNotice(`Chave válida (${result.apiKeyMasked}). Selecione os modelos e salve.`); const chats = result.models.filter((item) => !item.transcription); const whispers = result.models.filter((item) => item.transcription); if (!chats.some((item) => item.id === model)) setModel(chats.find((item) => item.id === "openai/gpt-oss-120b")?.id ?? chats[0]?.id ?? ""); if (!whispers.some((item) => item.id === transcriptionModel)) setTranscriptionModel(whispers.find((item) => item.id === "whisper-large-v3-turbo")?.id ?? whispers[0]?.id ?? ""); } catch (reason) { setError(message(reason)); } finally { setBusy(""); } }
  async function save() { setBusy("save"); setError(""); try { const result = await api<GroqStatus>("/groq/config", { method: "PUT", body: JSON.stringify({ ...(key ? { apiKey: key } : {}), model, transcriptionModel, temperature }) }); setKey(""); setStatus(result); setNotice("Configuração Groq validada e salva com segurança."); await load(); } catch (reason) { setError(message(reason)); } finally { setBusy(""); } }
  async function test() { setBusy("test"); setError(""); try { const result = await api<{ replyText: string; model: string }>("/groq/test", { method: "POST" }); setNotice(`Teste concluído com ${result.model}: ${result.replyText}`); await load(); } catch (reason) { setError(message(reason)); } finally { setBusy(""); } }
  const limits = status?.health.rateLimits;
  return <div className="page-stack"><PageHeader pageKey="groq" actions={<button className="hero-button" onClick={() => void load()}><RefreshCw /> Atualizar</button>} />
    {aiStatus ? <section className="card"><div className="integration-title"><span><Activity /></span><div><p>Roteamento de IA</p><h2>Groq principal · Gemini fallback</h2></div><b className={aiStatus.groq === "online" ? "positive" : "negative"}>Groq: {aiStatus.groq}</b></div><div className="diagnostic-metrics"><div><span>Gemini</span><strong>{aiStatus.gemini}</strong></div><div><span>Chamadas hoje</span><strong>{aiStatus.callsToday}</strong></div><div><span>Fallbacks hoje</span><strong>{aiStatus.fallbacksToday}</strong></div><div><span>Falhas finais</span><strong>{aiStatus.finalFailuresToday}</strong></div></div></section> : null}
    {error ? <Feedback kind="error" message={error} onClose={() => setError("")} /> : null}{notice ? <Feedback kind="success" message={notice} onClose={() => setNotice("")} /> : null}
    {status?.processingPaused ? <div className="safety-banner"><TriangleAlert /><div><strong>Processamento de IA pausado</strong><span>{status.lastFailure ?? "O modelo selecionado não está disponível. Escolha um modelo ativo para retomar."}</span></div></div> : null}
    {!status ? <section className="card"><SkeletonTable /></section> : <section className="groq-layout">
      <form className="card settings-form" onSubmit={(event) => { event.preventDefault(); void save(); }}><div className="integration-title"><span><Sparkles /></span><div><p>Provedor exclusivo</p><h2>GroqCloud</h2></div><b className={status.health.ok ? "positive" : "negative"}>{status.health.ok ? "Disponível" : "Indisponível"}</b></div><div className="form-grid">
        <label className="full">Chave da API<small>{status.configured ? `Salva como ${status.apiKeyMasked}. Digite somente para substituir.` : "A chave é validada no servidor e nunca volta inteira ao navegador."}</small><div className="secret-input"><KeyRound /><input aria-label="Chave da API Groq" type="password" autoComplete="off" value={key} placeholder={status.configured ? status.apiKeyMasked : "gsk_..."} onChange={(event) => setKey(event.target.value)} /><button type="button" className="secondary-button" onClick={() => void validate()} disabled={busy === "validate"}><CheckCircle2 /> {busy === "validate" ? "Validando..." : "Validar e listar"}</button></div></label>
        <label>Modelo principal<select value={model} onChange={(event) => setModel(event.target.value)}>{chatModels.map((item) => <option key={item.id} value={item.id}>{item.id}</option>)}</select><small>{chatModels.length} modelo(s) ativo(s) para texto nesta conta.</small></label>
        <label>Modelo de transcrição<select value={transcriptionModel} onChange={(event) => setTranscriptionModel(event.target.value)}>{whisperModels.map((item) => <option key={item.id} value={item.id}>{item.id}</option>)}</select><small>Somente modelos Whisper ativos são listados.</small></label>
        <label>Temperatura<input type="number" min="0" max="1" step="0.05" value={temperature} onChange={(event) => setTemperature(Number(event.target.value))} /></label>
      </div><footer className="settings-footer"><button type="button" className="secondary-button" onClick={() => void test()} disabled={Boolean(busy)}><Play /> Testar resposta</button><button className="primary-button" disabled={Boolean(busy) || !model || !transcriptionModel}><Save /> {busy === "save" ? "Salvando..." : "Salvar configuração"}</button></footer></form>
      <aside className="card groq-diagnostics"><header><Gauge /><div><p>Limites percebidos</p><h2>Última resposta da Groq</h2></div></header><div className="diagnostic-metrics"><div><span>Latência</span><strong>{status.health.latencyMs} ms</strong></div><div><span>Modelos ativos</span><strong>{status.health.modelCount}</strong></div><div><span>Requisições restantes</span><strong>{limits?.remainingRequests ?? "—"}</strong></div><div><span>Tokens restantes</span><strong>{limits?.remainingTokens ?? "—"}</strong></div><div><span>Reset de requisições</span><strong>{limits?.resetRequests ?? "—"}</strong></div><div><span>Reset de tokens</span><strong>{limits?.resetTokens ?? "—"}</strong></div></div><div className="last-failure"><Activity /><div><span>Última falha</span><strong>{status.lastFailure ?? status.health.error ?? "Nenhuma falha registrada"}</strong></div></div><p className="provider-note">Todas as requisições usam o SDK oficial <code>groq-sdk</code> e são enviadas somente à GroqCloud. IDs de modelo com “openai” continuam sendo modelos hospedados pela Groq.</p></aside>
    </section>}
  </div>;
}
function message(reason: unknown) { return reason instanceof Error ? reason.message : "Falha ao acessar a Groq."; }
