import { useEffect, useMemo, useState, type FormEvent } from "react";
import { BookOpen, FileText, Pencil, Plus, Trash2, UploadCloud } from "lucide-react";
import { Button, ConfirmDialog, EmptyState, FileUploader, FilterBar, Modal, SearchInput, StatusBadge } from "@renova123/ui";
import { api } from "../api";
import { Feedback } from "../components/Feedback";
import { PageHeader } from "../components/PageHeader";

type Item = { id: string; title: string; category: string; subject?: string; tags?: string[]; stages?: string[]; source?: string; content: string; active: boolean };
export function KnowledgePage() {
  const [rows, setRows] = useState<Item[]>([]); const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [stage, setStage] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const [remove, setRemove] = useState<Item | null>(null); const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { try { setRows((await api<{ rows: Item[] }>(`/knowledge?page=1&pageSize=100&search=${encodeURIComponent(search)}`)).rows); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao carregar conhecimento."); } }
  useEffect(() => { const timer = setTimeout(() => void load(), 180); return () => clearTimeout(timer); }, [search]);
  const visible = useMemo(() => rows.filter((item) => (!category || item.category === category) && (!stage || item.stages?.includes(stage))), [rows, category, stage]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { if (file && !editing) { form.set("file", file); await api("/knowledge/upload", { method: "POST", body: form }); } else { const body = { title: form.get("title"), category: form.get("category"), subject: form.get("subject"), tags: split(form.get("tags")), stages: split(form.get("stages")), source: editing?.source ?? "text", content: form.get("content"), active: true }; await api(editing ? `/knowledge/${editing.id}` : "/knowledge", { method: editing ? "PATCH" : "POST", body: JSON.stringify(body) }); } setOpen(false); setEditing(null); setFile(null); setMessage("Base de conhecimento atualizada."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao salvar."); } }
  async function archive() { if (!remove) return; try { await api(`/knowledge/${remove.id}`, { method: "DELETE" }); setMessage("Conteúdo arquivado."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao arquivar."); } }
  return <div className="page-stack"><PageHeader pageKey="knowledge" actions={<Button onClick={() => setOpen(true)}><Plus /> Novo conteúdo</Button>} />{error ? <Feedback kind="error" message={error} onClose={() => setError("")} /> : null}{message ? <Feedback kind="success" message={message} onClose={() => setMessage("")} /> : null}<FilterBar><SearchInput value={search} onChange={setSearch} placeholder="Buscar por texto, assunto ou tag" /><select value={category} onChange={(event) => setCategory(event.target.value)} aria-label="Categoria"><option value="">Todas as categorias</option>{[...new Set(rows.map((item) => item.category))].map((item) => <option key={item}>{item}</option>)}</select><input value={stage} onChange={(event) => setStage(event.target.value)} placeholder="Filtrar estágio" aria-label="Estágio" /></FilterBar><section className="knowledge-grid">{visible.length ? visible.map((item) => <article className="card knowledge-card" key={item.id}><header><span><BookOpen /></span><div><small>{item.category} • {item.subject || "Geral"}</small><h3>{item.title}</h3></div></header><p>{item.content || "Arquivo armazenado; edite para incluir o texto extraído."}</p><div className="tag-row">{item.tags?.map((tag) => <StatusBadge key={tag}>{tag}</StatusBadge>)}</div><footer><span>{item.stages?.join(" · ") || "Todos os estágios"}</span><button aria-label="Editar" onClick={() => { setEditing(item); setOpen(true); }}><Pencil /></button><button aria-label="Arquivar" onClick={() => setRemove(item)}><Trash2 /></button></footer></article>) : <EmptyState title="Nenhum conteúdo" description="Cadastre textos, FAQ, regras, PDFs ou apresentações." />}</section>
    <Modal open={open} title={editing ? "Editar conhecimento" : "Novo conhecimento"} description="Pesquisa textual e tags, sem dependência de embeddings." onClose={() => { setOpen(false); setEditing(null); setFile(null); }} size="large"><form className="operational-form" onSubmit={(event) => void save(event)}><div className="form-grid compact"><label>Título<input name="title" required defaultValue={editing?.title} /></label><label>Categoria<select name="category" required defaultValue={editing?.category ?? "FAQ"}><option>FAQ</option><option>Regra</option><option>Produto</option><option>Comercial</option><option>Documento</option><option>Apresentação</option></select></label><label>Assunto<input name="subject" defaultValue={editing?.subject} /></label><label>Tags<input name="tags" defaultValue={editing?.tags?.join(", ")} /></label><label>Estágios<input name="stages" defaultValue={editing?.stages?.join(", ")} /></label></div><label>Texto extraído/editável<textarea name="content" rows={10} defaultValue={editing?.content} required={!file} /></label>{!editing ? <FileUploader file={file} onChange={setFile} maxSizeMb={25} accept="text/*,.json,.pdf,.ppt,.pptx" icon={<UploadCloud />} description="Opcional: TXT, JSON, PDF ou apresentação. PDF/PPT fica disponível para revisão manual." /> : null}<footer className="modal-form-actions"><Button type="button" variant="secondary" onClick={() => setOpen(false)}>Cancelar</Button><Button><FileText /> Salvar</Button></footer></form></Modal><ConfirmDialog open={Boolean(remove)} title="Arquivar conteúdo?" description="Ele deixa de entrar no contexto do Francisco." confirmLabel="Arquivar" danger onConfirm={() => void archive()} onClose={() => setRemove(null)} />
  </div>;
}
function split(value: FormDataEntryValue | null) { return String(value ?? "").split(",").map((item) => item.trim()).filter(Boolean); }
