import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Archive, Eye, FileUp, History, Pencil, Plus, UploadCloud } from "lucide-react";
import { Button, ConfirmDialog, EmptyState, FileUploader, FilterBar, Modal, SearchInput, StatusBadge } from "@renova123/ui";
import { api } from "../api";
import { Feedback } from "../components/Feedback";
import { PageHeader } from "../components/PageHeader";

type Material = { id: string; name: string; description?: string; category: string; tags?: string[]; mimeType?: string; sizeBytes?: number; size?: string; active: boolean; autoSendAllowed?: boolean; humanConfirmationRequired?: boolean; allowedStages?: string[]; relatedIntent?: string; instruction?: string; archivedAt?: string | null };
type Result = { rows: Material[]; total: number };

export function MaterialsPage() {
  const [rows, setRows] = useState<Material[]>([]); const [search, setSearch] = useState(""); const [category, setCategory] = useState("");
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Material | null>(null); const [preview, setPreview] = useState<{ material: Material; url: string | null } | null>(null); const [history, setHistory] = useState<Record<string, unknown>[] | null>(null);
  const [file, setFile] = useState<File | null>(null); const [progress, setProgress] = useState(0); const [archive, setArchive] = useState<Material | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  async function load() { try { const data = await api<Result>(`/materials?page=1&pageSize=100&search=${encodeURIComponent(search)}`); setRows(data.rows.filter((row) => !row.archivedAt)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao carregar materiais."); } }
  useEffect(() => { const timer = setTimeout(() => void load(), 180); return () => clearTimeout(timer); }, [search]);
  const filtered = useMemo(() => rows.filter((row) => !category || row.category === category), [rows, category]);
  const categories = [...new Set(rows.map((row) => row.category))];
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setProgress(15); const form = new FormData(event.currentTarget); try { if (editing) { const values = { name: form.get("name"), description: form.get("description"), category: form.get("category"), tags: split(form.get("tags")), allowedStages: split(form.get("allowedStages")), relatedIntent: form.get("relatedIntent") || null, instruction: form.get("instruction"), active: form.get("active") === "true", autoSendAllowed: form.get("autoSendAllowed") === "true", humanConfirmationRequired: form.get("humanConfirmationRequired") === "true" }; setProgress(55); await api(`/materials/${editing.id}`, { method: "PATCH", body: JSON.stringify(values) }); } else { if (!file) throw new Error("Selecione um arquivo."); form.set("file", file); setProgress(45); await api("/materials", { method: "POST", body: form }); } setProgress(100); setSuccess(editing ? "Material atualizado." : "Material adicionado à biblioteca."); setOpen(false); setEditing(null); setFile(null); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao salvar material."); } finally { setBusy(false); setTimeout(() => setProgress(0), 500); } }
  async function showPreview(row: Material) { try { const data = await api<{ url: string | null }>(`/materials/${row.id}/preview`); setPreview({ material: row, url: data.url }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Prévia indisponível."); } }
  async function showHistory(row: Material) { try { setHistory((await api<{ rows: Record<string, unknown>[] }>(`/materials/${row.id}/history`)).rows); } catch (reason) { setError(reason instanceof Error ? reason.message : "Histórico indisponível."); } }
  async function confirmArchive() { if (!archive) return; try { await api(`/materials/${archive.id}`, { method: "DELETE" }); setSuccess("Material arquivado sem remover mensagens históricas."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Falha ao arquivar."); } }
  return <div className="page-stack"><PageHeader pageKey="materials" actions={<Button onClick={() => { setEditing(null); setOpen(true); }}><Plus /> Novo material</Button>} />
    {error ? <Feedback kind="error" message={error} onClose={() => setError("")} /> : null}{success ? <Feedback kind="success" message={success} onClose={() => setSuccess("")} /> : null}
    <FilterBar><SearchInput value={search} onChange={setSearch} placeholder="Buscar material, categoria ou tag" /><select aria-label="Categoria" value={category} onChange={(event) => setCategory(event.target.value)}><option value="">Todas as categorias</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></FilterBar>
    <section className="material-grid">{!rows.length && !error ? <EmptyState title="Biblioteca vazia" description="Envie o primeiro material autorizado." /> : filtered.map((row) => <article className="card material-card" key={row.id}><span><FileUp /></span><div><small>{row.category}</small><h3>{row.name}</h3><p>{row.description || row.mimeType}</p><div className="tag-row">{row.tags?.map((tag) => <StatusBadge key={tag}>{tag}</StatusBadge>)}</div></div><footer><StatusBadge tone={row.active ? "positive" : "neutral"}>{row.active ? "Ativo" : "Inativo"}</StatusBadge><b>{row.sizeBytes ? `${(row.sizeBytes / 1024 / 1024).toFixed(1)} MB` : row.size ?? "—"}</b></footer><div className="card-actions"><button aria-label="Pré-visualizar" onClick={() => void showPreview(row)}><Eye /></button><button aria-label="Histórico" onClick={() => void showHistory(row)}><History /></button><button aria-label="Editar" onClick={() => { setEditing(row); setOpen(true); }}><Pencil /></button><button aria-label="Arquivar" onClick={() => setArchive(row)}><Archive /></button></div></article>)}</section>
    <Modal open={open} title={editing ? "Editar material" : "Novo material"} description="Controle estágios, intenção e autorização de envio." onClose={() => { setOpen(false); setEditing(null); }} size="large"><form className="operational-form" onSubmit={(event) => void save(event)}><label>Nome<input name="name" required minLength={2} defaultValue={editing?.name} /></label><label>Descrição<textarea name="description" rows={3} defaultValue={editing?.description} /></label><div className="form-grid compact"><label>Categoria<input name="category" required defaultValue={editing?.category} /></label><label>Tags<input name="tags" defaultValue={editing?.tags?.join(", ")} /></label><label>Estágios permitidos<input name="allowedStages" defaultValue={editing?.allowedStages?.join(", ")} /></label><label>Intenção<input name="relatedIntent" defaultValue={editing?.relatedIntent} /></label></div><label>Instrução de uso<textarea name="instruction" rows={3} defaultValue={editing?.instruction} /></label>{!editing ? <FileUploader file={file} onChange={setFile} maxSizeMb={25} accept="image/*,video/*,audio/*,.pdf,.doc,.docx,.ppt,.pptx" icon={<UploadCloud />} description="Imagem, vídeo, áudio, PDF, documento ou apresentação • até 25 MB" /> : null}{progress ? <div className="upload-progress" role="progressbar" aria-valuenow={progress}><i style={{ width: `${progress}%` }} /></div> : null}<div className="toggle-list"><label><input type="checkbox" name="active" value="true" defaultChecked={editing?.active ?? true} /> Ativo</label><label><input type="checkbox" name="autoSendAllowed" value="true" defaultChecked={editing?.autoSendAllowed} /> Envio automático autorizado</label><label><input type="checkbox" name="humanConfirmationRequired" value="true" defaultChecked={editing?.humanConfirmationRequired ?? true} /> Exigir confirmação humana</label></div><footer className="modal-form-actions"><Button type="button" variant="secondary" onClick={() => setOpen(false)}>Cancelar</Button><Button disabled={busy}>{busy ? "Salvando…" : "Salvar"}</Button></footer></form></Modal>
    <Modal open={Boolean(preview)} title={preview?.material.name ?? "Prévia"} onClose={() => setPreview(null)} size="large">{preview?.url ? preview.material.mimeType?.startsWith("image/") ? <img className="material-preview" src={preview.url} alt={preview.material.name} /> : preview.material.mimeType?.startsWith("video/") ? <video className="material-preview" src={preview.url} controls /> : preview.material.mimeType?.startsWith("audio/") ? <audio src={preview.url} controls /> : <iframe className="material-preview-frame" src={preview.url} title={preview.material.name} /> : <EmptyState title="Prévia simulada" description="O arquivo real estará disponível após configurar o Storage." />}</Modal>
    <Modal open={history !== null} title="Histórico de envio" onClose={() => setHistory(null)}>{history?.length ? history.map((item, index) => <article className="history-row" key={String(item.id ?? index)}><strong>{String(item.status)}</strong><span>{String(item.mode)} • {new Date(String(item.createdAt ?? item.created_at)).toLocaleString("pt-BR")}</span></article>) : <EmptyState title="Sem envios" description="Este material ainda não foi enviado." />}</Modal>
    <ConfirmDialog open={Boolean(archive)} title="Arquivar material?" description="Ele deixa de ser enviado, mas mensagens e histórico permanecem íntegros." confirmLabel="Arquivar" danger onConfirm={() => void confirmArchive()} onClose={() => setArchive(null)} />
  </div>;
}
function split(value: FormDataEntryValue | null) { return String(value ?? "").split(",").map((item) => item.trim()).filter(Boolean); }
